### PR TITLE
bpf: support JumpIf on RegX instead of K

### PR DESCRIPTION
**Pull request by arthurfabre**
Add a JumpIfX instruction which implements conditional jumps using
RegA and RegX. This is in addition to the pre-existing JumpIf
instruction which uses RegA and K.

This instruction / addressing mode is not mentionned in the original BPF
paper, but is supported by tools like bpf_asm, and has recently been
added to the kernel's filter.txt.

Simplify some of the parsing logic, and add a separate helper for
checking for "fake" JumpIfs.

Add JumpIfX support to the BPF vm.

Update testdata with JumpIfX instructions, and add tests
for both the assembler/disassembler and vm.

Fixes golang/go#27814

### CODE REVIEW

**Comment by arthurfabre** [comment]
CLA signed

**Comment by arthurfabre** [comment]
Any update on this? Happy to address any concerns.

**Comment by bradfitz** [comment]
@arthurfabre, the "bpf" package is not a core part of Go and is maintained by two volunteers who aren't on the Go team. You'll need to wait for @mdlayher or @danderson to find time.

**Comment by arthurfabre** [comment]
Thanks for taking a look!
I copied all the JumpIf tests and adapted them for JumpIfX (which I should have done from the start really, I was being lazy..).

Updating filter.txt is a good idea, I'll send a patch

**Comment by arthurfabre** [comment]
`filter.txt` has been updated to document `JumpIfX`: https://patchwork.ozlabs.org/patch/980025/

**Pull request closed without merging**
