### PR TITLE
add http2 health check parameters for ConfigureTransport

### PR DESCRIPTION
**Pull request by duyanghao**
Currently, `ConfigureTransport` can't configure http2 health check parameters(i.e. http2.Transport.ReadIdleTimeout and http2.Transport.PingTimeout). 
This PR add http2 health check transportOption for ConfigureTransport when configures a net/http HTTP/1 Transport to use HTTP/2. 

Signed-off-by: duyanghao <1294057873@qq.com>

### CODE REVIEW

**Comment by duyanghao** [comment]
@googlebot I signed it!

**Comment by caesarxuchao** [comment]
This seems duplicate of https://github.com/golang/net/pull/74.

**Comment by caesarxuchao** [comment]
(I don't mind abandoning #74 if you can get this one in :)

**Comment by duyanghao** [comment]
> (I don't mind abandoning #74 if you can get this one in :)

I'd be delighted to do so.

**Comment by duyanghao** [comment]
@bradfitz Please have a check for this PR.

**Pull request closed without merging**
